---
title: "Beräkningar inlämningsuppgift 1"
author: "Erik Ödmann, David Carlsson"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exponentialfördelningen

## Täthetsfunktionen

$$
p_X(x) = \lambda e^{-\lambda x}, \quad x \ge 0
$$

## Likelihood för en observation

$$
L(\lambda) = \lambda e^{-\lambda x}
$$

## Log-likelihood för en observation

$$
\begin{aligned}
l(\lambda) &= \ln(\lambda e^{-\lambda x}) \\
           &= \ln(\lambda) + \ln(e^{-\lambda x}) \\
           &= \ln(\lambda) - \lambda x \ln(e) \\
           &= \ln(\lambda) - \lambda x 
\end{aligned}
$$

## Log-likelihood för hela urvalet

$$
\begin{aligned}
l_n(\lambda) &= \sum_{i=1}^{n}(\ln(\lambda) - \lambda x) \\
             &= n\ln(\lambda) - \lambda\sum_{i=1}^{n}x_i
\end{aligned}
$$

## Första derivatan av likelihood funktionen för urvalet

$$
\begin{aligned}
l'_n(\lambda) &= \frac{d }{d\lambda}(n\ln(\lambda) - \lambda\sum_{i=1}^{n}x_i) \\
              &= n\lambda^{-1} - \sum_{i=1}^{n}x_i 
\end{aligned}
$$

## ML skattningen ges utav att lösa 

$$
\begin{aligned}
l'_n(\lambda) &= n\lambda^{-1} - \sum_{i=1}^{n}x_i = 0 \\
              &\Leftrightarrow \sum_{i=1}^{n}x_i = \frac{n}{\lambda} \\
              &\Leftrightarrow \hat\lambda = \frac{n}{\sum_{i=1}^{n}x_i}
\end{aligned}
$$

## För att beräkna fisherinformationen behöver vi andraderivatan utav log-likelihood funktionen

$$
\begin{aligned}
l''_n(\lambda) &= \frac{d }{d\lambda}(n\lambda^{-1} - \sum_{i=1}^{n}x_i) \\
               &= -n\lambda^{-2} 
\end{aligned}
$$

## Fisherinformationen för urvalet blir då

$$
\begin{aligned}
I_n(\lambda) &= - E[l''_n(\lambda)] \\
             &= - E[-n\lambda^{-2}] \\
             &= n\lambda^{-2}
\end{aligned}
$$

## Medelfelet för ML-skattningen ges då utav

$$
\begin{aligned}
Sd(\hat\lambda) &= I_n(\hat\lambda)^{-1/2} \\
                &= (n\hat\lambda^{-2})^{-1/2} \\
                &= \hat\lambda n^{-1/2}
\end{aligned}
$$

\newpage

# Binomialfördelningen

## Täthetsfunktionen

$$
p_X(k) = {n \choose k} p^k(1 - p)^{n - k}, \quad k=\text{Antal utfall}
$$

## Likelihood för hela urvalet

$$
L_n(p) = {n \choose k} p^k(1 - p)^{n - k}
$$

## Log-likelihood för hela urvalet

$$
\begin{aligned}
l_n(p) &= \ln({n \choose k} p^k(1 - p)^{n - k}) \\
     &= \ln({n \choose k}) + \ln(p^k) + \ln((1 - p)^{n - k}) \\
     &= \ln({n \choose k}) + k\ln(p) + (n - k)\ln(1-p)
\end{aligned}
$$

## Första derivatan utav log-likelihood funktionen för hela urvalet

$$
\begin{aligned}
l'_n(p) &= \frac{d }{dp}(\ln({n \choose k}) + k\ln(p) + (n - k)\ln(1-p)) \\
            &= kp^{-1} - (n - k)(1 - p)^{-1}
\end{aligned}
$$

## ML-skattninges ges utav att lösa ekvationen för p

$$
\begin{aligned}
l'_n(p) &= kp^{-1} - (n - k)(1 - p)^{-1} = 0 \\
        &\Leftrightarrow kp^{-1} = (n - k)(1 - p)^{-1} \\
        &\Leftrightarrow (1-p)k = p(n-k) \\
        &\Leftrightarrow k - pk = pn - pk \\
        &\Leftrightarrow k = pn \\
        &\Leftrightarrow \hat p = \frac{k}{n}
\end{aligned}
$$
## För att beräkna fisherinformationen behöver vi andraderivatan utav log-likelihood funktionen

$$
\begin{aligned}
l''_n(p) &= \frac{d }{dp}(kp^{-1} - (n - k)(1 - p)^{-1}) \\
         &= -kp^{-2} - (n - k)(1 - p)^{-2}
\end{aligned}
$$

## Fisherinformationen för hela urvalet blir då

$$
\begin{aligned}
I_n(p) &= - E[l''_n(p)] \\
             &= -E[-kp^{-2} - (n - k)(1 - p)^{-2}] \\
             &= -E[\frac{-k + 2kp - np^2}{p^2(1-p)^2}] \\
\end{aligned}
$$

Eftersom $E[k] = np$ får vi

$$
\begin{aligned}
I_n(p) &= \frac{np + np^2}{p^2(1-p)^2} \\
       &= \frac{n}{p(1-p)}
\end{aligned}
$$

## Medelfelet för ML-skattningen ges då utav

$$
\begin{aligned}
Sd(\hat p) &= I_n(\hat p)^{-1/2} \\
           &= \sqrt{\frac{\hat p(1-\hat p)}{n}} \\
\end{aligned}
$$
